begin;
select plan(21);
insert into auth.users (id, email) values ('aaaaaa27-0000-0000-0000-000000000001','user@x.test'),('aaaaaa27-0000-0000-0000-000000000002','support@x.test'),('aaaaaa27-0000-0000-0000-000000000007','admin@x.test');
insert into platform_roles (user_id, role) values ('aaaaaa27-0000-0000-0000-000000000002','support'),('aaaaaa27-0000-0000-0000-000000000007','admin');

set local role authenticated;
select set_config('request.jwt.claim.sub','aaaaaa27-0000-0000-0000-000000000001',true);
select throws_ok($$select admin_save_category(null,'t-cat-27','Test Category',null,1,true,'a valid reason here')$$, '42501', null, 'a user cannot save a category');
select set_config('request.jwt.claim.sub','aaaaaa27-0000-0000-0000-000000000002',true);
select set_config('request.jwt.claims','{"aal":"aal2"}',true);
select throws_ok($$select admin_save_skill(null,'t-skill-27','Test Skill',null,true,'a valid reason here')$$, '42501', null, 'support cannot save a skill');
select set_config('request.jwt.claim.sub','aaaaaa27-0000-0000-0000-000000000007',true);
select set_config('request.jwt.claims','{}',true);
select throws_ok($$select admin_save_category(null,'t-cat-27','Test Category',null,1,true,'a valid reason here')$$, '42501', null, 'admin without aal2 is refused');
select set_config('request.jwt.claims','{"aal":"aal2"}',true);
select throws_ok($$select admin_save_category(null,'Bad Slug','Test Category',null,1,true,'a valid reason here')$$, '22023', null, 'an invalid slug is refused');
select throws_ok($$select admin_save_category(null,'t-cat-27','x',null,1,true,'a valid reason here')$$, '22023', null, 'a short name is refused');
select throws_ok($$select admin_save_category(null,'t-cat-27','Test Category',null,1,true,'short')$$, '22023', null, 'a short reason is refused');
select lives_ok($$select admin_save_category(null,'t-cat-27','Test Category',null,1,true,'Adding a category for tests')$$, 'admin creates a category');
select lives_ok($$select admin_save_category(null,'t-sub-27','Test Sub',(select id from categories where slug = 't-cat-27'),2,true,'Adding a child category')$$, 'admin creates a child category');
select throws_ok($$select admin_save_category(null,'t-cat-27','Duplicate',null,1,true,'a valid reason here')$$, '22023', null, 'a duplicate slug is refused');
select throws_ok($$select admin_save_category(null,'t-deep-27','Too Deep',(select id from categories where slug = 't-sub-27'),1,true,'a valid reason here')$$, '22023', null, 'a third level is refused');
select throws_ok($$select admin_save_category((select id from categories where slug = 't-cat-27'),null,'Test Category',(select id from categories where slug = 't-sub-27'),1,true,'a valid reason here')$$, '22023', null, 'a parent cannot move under its own child');
select lives_ok($$select admin_save_category((select id from categories where slug = 't-sub-27'),null,'Renamed Sub',(select id from categories where slug = 't-cat-27'),5,true,'Renaming the child category')$$, 'admin renames a category');
select throws_ok($$select admin_save_category((select id from categories where slug = 't-sub-27'),'other-slug','Renamed Sub',null,5,true,'a valid reason here')$$, '22023', null, 'a slug cannot change');
select lives_ok($$select admin_save_skill(null,'t-skill-27','Test Skill',(select id from categories where slug = 't-cat-27'),true,'Adding a skill for tests')$$, 'admin creates a skill');
select lives_ok($$select admin_save_skill((select id from skills where slug = 't-skill-27'),null,'Test Skill',(select id from categories where slug = 't-cat-27'),false,'Retiring the skill first')$$, 'admin deactivates the skill first');
select lives_ok($$select admin_save_category((select id from categories where slug = 't-sub-27'),null,'Renamed Sub',(select id from categories where slug = 't-cat-27'),5,false,'Retiring the child first')$$, 'admin deactivates the child category first');
select lives_ok($$select admin_save_category((select id from categories where slug = 't-cat-27'),null,'Test Category',null,1,false,'Retiring the category')$$, 'admin deactivates a category once nothing active is under it');
select throws_ok($$select admin_save_skill((select id from skills where slug = 't-skill-27'),null,'Test Skill',(select id from categories where slug = 't-cat-27'),true,'a valid reason here')$$, '22023', null, 'a skill cannot be active under an inactive category');
select throws_ok($$update categories set name = 'Hacked name' where slug = 't-cat-27'$$, '42501', null, 'an admin cannot write categories directly');
select throws_ok($$update skills set name = 'Hacked name' where slug = 't-skill-27'$$, '42501', null, 'an admin cannot write skills directly');
reset role;
select is((select count(*)::int from audit_log where action in ('admin.category.save','admin.skill.save') and after ->> 'reason' is not null), 7, 'every save is audited with its reason');
select * from finish();
rollback;
